source ~/.dotfiles/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Syntax highlighting bundle.
antigen bundle archlinux
antigen bundle git
antigen bundle git-flow
antigen bundle gitignore
antigen bundle history
antigen bundle systemd
antigen bundle github
antigen bundle tmux
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle laravel5
antigen bundle npm
antigen bundle composer
antigen bundle command-not-found
antigen bundle extract
# Load the theme.
antigen theme agnoster

# Tell antigen that you're done.
antigen apply

alias vi=vim
